### ISSUE TITLE
Add support for npm

### ISSUE THREAD

**Issue by judasane** [anseki/eager-image-loader#1]
It would be great if it was possible to install from npm, so it could be easier to integrate to projects and mantain code.

**Comment by anseki** [comment]
Hi @judasane, thank you for the comment.
So, did you mean that you couldn't install it from NPM?
The NPM URL (https://www.npmjs.com/package/eager-image-loader) is linked from this document: https://anseki.github.io/eager-image-loader/

**Comment by judasane** [comment]
Thanks a lot. I think the problem is about documentation. I've just seen the link to npm (is a little button), so you could include a title in your readme, something like "Installation" to make it more explicit  and it would be great!
I'm gonna test it

**Comment by anseki** [comment]
Thank you for the suggestion.
I think that's enough for now because the NPM badge is very popular and containing a file `package.json` means that it is published in NPM.
However, I will rethink that if more request comes.

So, please close this issue if it was already solved.
