### ISSUE TITLE
issue on Edge browser

### ISSUE THREAD

**Issue by huannguyenfit** [anseki/eager-image-loader#2]
I try to implement eager-image-loader with angularjs + requirejs, but IE or Edge not working. (It works in both chrome and firefox)

`<img src="https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif" ng-click="vm.showImages($event, x + 1)" data-src=" {{vm.getCaseImageId(x)}}" onerror="src='/Content/images/photo-not-avalable.jpg'" >`

at angularjs

`  define(['angularAMD',  'eagerImageLoader'], function(angularAMD){
        angularAMD.controller(controllerId,  function() {     
        var vm = this;
        vm.getCaseImageId = function(){
              do something after return src
               => return src = http://www.xxxx.com/api/media/...
       }
}`

**Comment by anseki** [comment]
Hi @huannguyenfit, thank you for the report.
So, what does the "not working" mean? An error occurred, just that doesn't start, etc.

**Comment by huannguyenfit** [comment]
Hi. It doesn't start, just  show loading image only.

**Comment by anseki** [comment]
Both IE and Edge worked fine in my environment.
Try this example:
https://jsfiddle.net/q5j6yszL/

**Comment by anseki** [comment]
Or, open this page via IE and Edge.
https://anseki.github.io/eager-image-loader/

**Comment by anseki** [comment]
No reply came, and I close this issue.
